"""The contract between the app and the desktop's media integration.

Two sides, both Protocols so the backends need neither Textual nor tidalapi:
`PlayerBackend` is what a backend may ask of the app (the app's `mpris_*`
methods), and `MediaService` is what the app asks of a backend. MPRIS over
D-Bus on Linux and, in time, SMTC on Windows sit behind the same pair; the
`mpris_` prefix is the adapter's name and keeps it whatever the system.
"""

from __future__ import annotations

from typing import Any, Protocol


class PlayerBackend(Protocol):
    """What the media service needs from the application."""

    def mpris_status(self) -> str: ...
    def mpris_metadata(self) -> dict[str, Any]: ...
    def mpris_position(self) -> float: ...
    def mpris_volume(self) -> float: ...
    def mpris_set_volume(self, value: float) -> None: ...
    def mpris_rate(self) -> float: ...
    def mpris_set_rate(self, value: float) -> None: ...
    def mpris_loop_status(self) -> str: ...
    def mpris_set_loop_status(self, value: str) -> None: ...
    def mpris_shuffle(self) -> bool: ...
    def mpris_set_shuffle(self, value: bool) -> None: ...
    def mpris_can_go_next(self) -> bool: ...
    def mpris_can_go_previous(self) -> bool: ...
    def mpris_play(self) -> None: ...
    def mpris_pause(self) -> None: ...
    def mpris_play_pause(self) -> None: ...
    def mpris_stop(self) -> None: ...
    def mpris_next(self) -> None: ...
    def mpris_previous(self) -> None: ...
    def mpris_seek(self, offset: float) -> None: ...
    def mpris_set_position(self, position: float) -> None: ...
    def mpris_quit(self) -> None: ...
    def mpris_track_ids(self) -> list[str]: ...
    def mpris_tracks(self) -> list[dict[str, Any]]: ...
    def mpris_go_to(self, track_id: str) -> None: ...


class MediaService(Protocol):
    """What the app needs from the desktop's media integration."""

    @property
    def shared(self) -> bool:
        """Whether another tidalamp already held the name, and this one took
        another. Always False where there is no name to share."""
        ...

    async def start(self) -> str:
        """Connect. Returns the name taken, "" where there is none; raises
        when there is no integration, which the app reports and survives."""
        ...

    async def stop(self) -> None: ...
    def publish(self) -> None: ...
    def publish_tracks(self) -> None: ...
    def seeked(self, position: float) -> None: ...
